version: 2.1

jobs:
  lint:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    - run: sudo pip install flake8
    - run: flake8

  unit-tests:
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt install -y mariadb-server
    - run: sudo pip install -r requirements-dev.txt
    - run: ./run_ci.sh
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: ./coverage.xml

workflows:
  build:
      jobs:
      - lint
      - unit-tests:
          requires:
          - lint
